# Generated by Django 4.2.2 on 2023-06-24 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='Введите уникальный юзернейм', max_length=150, unique=True, verbose_name='Имя пользователя'),
        ),
    ]
