# Generated by Django 4.2.2 on 2023-06-16 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Введите эл. почту', max_length=150, unique=True, verbose_name='Эл. почта'),
        ),
        migrations.AlterField(
            model_name='user',
            name='firstname',
            field=models.CharField(help_text='Введите имя', max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='lastname',
            field=models.CharField(help_text='Введите фамилию', max_length=100, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='Введите имя пользователя', max_length=100, unique=True, verbose_name='Логин'),
        ),
    ]
